[2021-11-21 11:45:59,409][main.py 17][INFO]: 
                     _    _         _      _____         _
      __ _ _ __ (_)  / \  _   _| |_ __|_   _|__  ___| |_
     / _` | '_ \| | / _ \| | | | __/ _ \| |/ _ \/ __| __|
    | (_| | |_) | |/ ___ \ |_| | || (_) | |  __/\__ \ |_
     \__,_| .__/|_/_/   \_\__,_|\__\___/|_|\___||___/\__|
          |_|
          Starting     ...  道长伴你终身   ...  测试之道学院永相随   ...
        
[2021-11-21 11:46:03,743][logger.py 62][INFO]: ------开始执行test_get_auth_code用例------
[2021-11-21 11:46:03,773][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:03,773][logger.py 70][INFO]: ------assert_api执行成功------
[2021-11-21 11:46:03,784][logger.py 70][INFO]: ------test_get_auth_code执行成功------
[2021-11-21 11:46:03,787][logger.py 62][INFO]: ------开始执行test_admin_login用例------
[2021-11-21 11:46:03,844][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:03,844][logger.py 70][INFO]: ------assert_api执行成功------
[2021-11-21 11:46:03,844][logger.py 70][INFO]: ------test_admin_login执行成功------
[2021-11-21 11:46:03,853][logger.py 62][INFO]: ------开始执行test_admin_login用例------
[2021-11-21 11:46:03,902][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:03,902][logger.py 70][INFO]: ------assert_api执行成功------
[2021-11-21 11:46:03,902][logger.py 70][INFO]: ------test_admin_login执行成功------
[2021-11-21 11:46:03,907][logger.py 62][INFO]: ------开始执行test_admin_login用例------
[2021-11-21 11:46:03,951][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:03,951][logger.py 70][INFO]: ------assert_api执行成功------
[2021-11-21 11:46:03,951][logger.py 70][INFO]: ------test_admin_login执行成功------
[2021-11-21 11:46:04,046][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:04,046][logger.py 70][INFO]: ------assert_api执行成功------
[2021-11-21 11:46:04,051][logger.py 62][INFO]: ------开始执行test_admin_login用例------
[2021-11-21 11:46:04,094][logger.py 62][INFO]: ------开始执行assert_api用例------
[2021-11-21 11:46:04,094][logger.py 66][ERROR]: ------assert_api用例执行失败，失败原因：------
[2021-11-21 11:46:04,096][logger.py 67][ERROR]: assert_api 用例 is error,here are details:Traceback (most recent call last):
  File "D:\daima\xin-daima\two-pytest-api-automation\common\logger.py", line 64, in log
    func(*args, **kwargs)
  File "D:\daima\xin-daima\two-pytest-api-automation\common\assert_api.py", line 35, in assert_api
    raise e
  File "D:\daima\xin-daima\two-pytest-api-automation\common\assert_api.py", line 26, in assert_api
    assert j == b[i]
AssertionError

[2021-11-21 11:46:04,096][logger.py 66][ERROR]: ------test_admin_login用例执行失败，失败原因：------
[2021-11-21 11:46:04,096][logger.py 67][ERROR]: test_admin_login 用例 is error,here are details:Traceback (most recent call last):
  File "D:\daima\xin-daima\two-pytest-api-automation\common\logger.py", line 64, in log
    func(*args, **kwargs)
  File "D:\daima\xin-daima\two-pytest-api-automation\case\test_receiving\test_add_address.py", line 38, in test_admin_login
    assert_api(actual_data,case_data['expect'])
  File "D:\daima\xin-daima\two-pytest-api-automation\common\logger.py", line 68, in log
    raise e
  File "D:\daima\xin-daima\two-pytest-api-automation\common\logger.py", line 64, in log
    func(*args, **kwargs)
  File "D:\daima\xin-daima\two-pytest-api-automation\common\assert_api.py", line 35, in assert_api
    raise e
  File "D:\daima\xin-daima\two-pytest-api-automation\common\assert_api.py", line 26, in assert_api
    assert j == b[i]
AssertionError

