{"uuid": "badc1098-689c-4fe6-b80a-653e16612605", "children": ["c7fab5dc-19d6-4ad8-a8a7-e3615059b568", "c453befd-6d17-4598-91fe-7ff700694242", "9e89318b-d3d5-4d64-868f-661b210d9c84"], "befores": [{"name": "als_login", "status": "broken", "statusDetails": {"message": "NameError: name 'clent1' is not defined\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\conftest.py\", line 30, in als_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 84, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 47, in __init__\n    result = login1(username=self.username, password=self.password)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 36, in login1\n    url = clent1.get_full_url(url, etc=etc)\n"}, "start": 1648177993747, "stop": 1648177993747}], "start": 1648177993747, "stop": 1648177993846}