{"uuid": "76060c3e-bdc6-43d8-8f66-beb50e052845", "children": ["99932d1c-a729-41f2-94ab-ef7bb5bba3d4", "df4c15b4-5fec-4447-9cf5-cfbecd44d0e3", "fe52ee0d-a253-4802-af3f-c64967d6c303"], "befores": [{"name": "als_login", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable\n", "trace": "  File \"D:\\ruanjian\\python\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\ruanjian\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 932, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\conftest.py\", line 30, in als_login\n    login_ls(lisi_info,'lisi_token')\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 84, in login_ls\n    return Login(admin_info,ls_token)\n  File \"D:\\daima\\xin-daima\\two-pytest-api-automation2\\common\\logintoken.py\", line 47, in __init__\n    result = login(username=self.username, password=self.password)\n"}, "start": 1648177936926, "stop": 1648177936926}], "start": 1648177936926, "stop": 1648177937016}